name: Deploy to InfinityFree

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.epizy.com
          username: ${{ secrets.INFINITYFREE_USERNAME }}
          password: ${{ secrets.INFINITYFREE_PASSWORD }}
          local-dir: .
          server-dir: /htdocs
          exclude: |
            .git/
            .github/
            node_modules/